In [6]:
import numpy as np
# Create matrices
A= np.array([[2, 2], [3, 3]])
B = np.array([[4, 4], [5, 5]])
#Addition 
D = A + B 
#Subtraction
D = A - B
#Multiplication(element-wise)
E = A * B
#Matrix multiplication
F = np.dot(A,B)# or A @ B
#Transpose
A_transpose = A.T
print("---ADDITION---")
print(C)
print("\n---SUBSTRACTION---")
print(D)
print("\n---ELEMENT WISE MULTIPLICATION---")
print(E)
print("\n---MATRIX MULTIPLICATION---")
print(F)
print("\n---TRANSPOSE---")
print(A_transpose)
print("\n ----USING SVD----")
# Create a sample matrix
X = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
# Perform SVD
U, S, VT = np.linalg.svd(X)
# Choose the number of components to keep (e.g., 3)
n_components = 3
#Reconstruct the matrix with reduced dimensions
X_reconstructed = np.dot(U[:, :n_components], np.dot(np.diag(S[:n_components]),
VT[:n_components, :])) 
print("\nOriginal Matrix:")
print(X)
print("\nReconstructed Matrix (with reduced dimensions):") 
print(X_reconstructed)

---ADDITION---
[[6 6]
 [8 8]]

---SUBSTRACTION---
[[-2 -2]
 [-2 -2]]

---ELEMENT WISE MULTIPLICATION---
[[ 8  8]
 [15 15]]

---MATRIX MULTIPLICATION---
[[18 18]
 [27 27]]

---TRANSPOSE---
[[2 3]
 [2 3]]

 ----USING SVD----

Original Matrix:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Reconstructed Matrix (with reduced dimensions):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
